### ISSUE TITLE
Leak and FD leaks when server host name is invalid

### ISSUE THREAD

**Issue by Tsunghao-C** [BenjaminHThomas/WebServer#14]
If Nth Server hostname in the config is invlaid, then all the previous Servers created will leak.

**Comment by nyzss** [comment]
should be fixed with #25

**Comment by nyzss** [comment]
should be fixed with #25 [671487f](https://github.com/BenjaminHThomas/WebServer/pull/25/commits/671487f53d597cc9797c91a187c5690fd6a651ac)
